#!/usr/bin/env python3
"""2.8.Sidebar refactor.

Splits `render()` into `render()` (one-time: header + persistent list
container) and `renderList()` (re-creates only the list children). The
search input lives inside the header, which is never re-created, so it
keeps focus across keystrokes.

Also changes Fuse config in vault-indexer.ts: minMatchCharLength 2 -> 1,
threshold 0.35 -> 0.4, so 1-character queries return hits.
"""
from pathlib import Path
import re

ROOT = Path('src/ui/views/projects-sidebar-view.ts')

src = ROOT.read_text()

# --- 1. Update event-bus subscriptions: only `projectChanged` does a full
# render (so the search input is fresh for the new project). All paper /
# index updates do `renderList()` only. -------------------------------
old_subs = (
    "    this.unsubscribers.push(\n"
    "      this.rv.eventBus.on('paperImported', () => this.render()),\n"
    "      this.rv.eventBus.on('paperUpdated', () => this.render()),\n"
    "      this.rv.eventBus.on('paperRemoved', () => this.render()),\n"
    "      this.rv.eventBus.on('paperStatusChanged', () => this.render()),\n"
    "      this.rv.eventBus.on('projectChanged', () => this.render()),\n"
    "      // Refresh results list when the indexer adds/removes/rebuilds records\n"
    "      // (e.g. a quote was captured while the user is mid-typing a query).\n"
    "      this.rv.eventBus.on('indexUpdated', () => this.render()),\n"
    "    );\n"
)
new_subs = (
    "    // Most updates only need to refresh the paper list — the header (with\n"
    "    // the search input) is rendered once on `onOpen` and stays mounted\n"
    "    // so its focus is never blown away by a re-render. `projectChanged`\n"
    "    // does a full re-render because switching projects should also clear\n"
    "    // any in-flight search query.\n"
    "    this.unsubscribers.push(\n"
    "      this.rv.eventBus.on('paperImported', () => this.renderList()),\n"
    "      this.rv.eventBus.on('paperUpdated', () => this.renderList()),\n"
    "      this.rv.eventBus.on('paperRemoved', () => this.renderList()),\n"
    "      this.rv.eventBus.on('paperStatusChanged', () => this.renderList()),\n"
    "      this.rv.eventBus.on('projectChanged', () => {\n"
    "        this.currentQuery = '';\n"
    "        this.render();\n"
    "      }),\n"
    "      // Refresh results list when the indexer adds/removes/rebuilds records\n"
    "      // (e.g. a quote was captured while the user is mid-typing a query).\n"
    "      this.rv.eventBus.on('indexUpdated', () => this.renderList()),\n"
    "    );\n"
)
assert src.count(old_subs) == 1, f"subscriptions block not found uniquely ({src.count(old_subs)})"
src = src.replace(old_subs, new_subs, 1)

# --- 2. Search-input listener: render() -> renderList() ---------------
old_search = (
    "      this.searchDebounce = window.setTimeout(() => {\n"
    "        this.searchDebounce = null;\n"
    "        this.render();\n"
    "      }, 80);\n"
)
new_search = (
    "      this.searchDebounce = window.setTimeout(() => {\n"
    "        this.searchDebounce = null;\n"
    "        this.renderList();\n"
    "      }, 80);\n"
)
assert src.count(old_search) == 1, f"search listener block not found ({src.count(old_search)})"
src = src.replace(old_search, new_search, 1)

# --- 3. Replace the render() body with the slim header-only version +
# add renderList() right after. --------------------------------------
# Use the comment header line as the anchor; everything after it (up to
# the closing `}` of render()) is the body.
old_body_start = (
    "  private render(): void {\n"
    "    const { contentEl } = this;\n"
    "    contentEl.empty();\n"
    "    contentEl.addClass('researchvault-sidebar');\n"
    "\n"
    "    this.renderHeader(contentEl);\n"
    "\n"
    "    const active = this.rv.projectManager.getActiveProject();\n"
    "    if (!active) {\n"
    "      contentEl.createEl('p', {\n"
    "        text: 'No active project. Use the \"switch active project\" command to pick one.',\n"
    "        cls: 'researchvault-sidebar-empty',\n"
    "      });\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    const papers = this.rv.paperService.getInProject(active.id);\n"
    "    if (papers.length === 0) {\n"
    "      contentEl.createEl('p', {\n"
    "        text: 'No papers in this project yet. Use \"add paper\" to import one.',\n"
    "        cls: 'researchvault-sidebar-empty',\n"
    "      });\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // When the user has typed a query, the indexer gives us a fuzzy-matched\n"
    "    // subset across the whole vault. We still constrain by active project\n"
    "    // membership at render time so the user never sees a paper from a\n"
    "    // different project mixed in.\n"
    "    const trimmed = this.currentQuery.trim();\n"
    "    if (trimmed) {\n"
    "      const hits = this.rv.vaultIndexer.searchPapers(trimmed);\n"
    "      const activePapers = new Set(papers.map((p) => p.id));\n"
    "      const scoped = hits.filter((p) => activePapers.has(p.id));\n"
    "      if (scoped.length === 0) {\n"
    "        contentEl.createEl('p', {\n"
    "          text: `No papers match \"${trimmed}\" in this project.`,\n"
    "          cls: 'researchvault-sidebar-empty',\n"
    "        });\n"
    "        return;\n"
    "      }\n"
    "      this.renderGroup(contentEl, 'results', scoped);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // Derived \"Needs action\" group. Computed every render (cheap; it's just\n"
    "    // a filter + sort over the in-memory list). Empty -> nothing rendered.\n"
    "    const needsAction = computeNeedsAction(papers);\n"
    "    if (needsAction.length > 0) {\n"
    "      this.renderGroup(contentEl, 'needs-action', needsAction);\n"
    "    }\n"
    "\n"
    "    const groups = groupByStatus(papers);\n"
    "    for (const status of STATUS_ORDER) {\n"
    "      const rows = groups.get(status);\n"
    "      if (!rows || rows.length === 0) continue;\n"
    "      this.renderGroup(contentEl, status, rows);\n"
    "    }\n"
    "  }\n"
)
new_body_start = (
    "  /**\n"
    "   * Full re-render of the sidebar. Called on `onOpen` and on project switch.\n"
    "   * For in-place updates (search filter, paper import, status change,\n"
    "   * indexer refresh) call `renderList()` instead so the header (and the\n"
    "   * search input focused inside it) is never blown away.\n"
    "   */\n"
    "  private render(): void {\n"
    "    const { contentEl } = this;\n"
    "    contentEl.empty();\n"
    "    contentEl.addClass('researchvault-sidebar');\n"
    "\n"
    "    // Header is mounted once per full render. It contains the search\n"
    "    // input; leaving it mounted across keystrokes is what keeps the input\n"
    "    // focused.\n"
    "    this.renderHeader(contentEl);\n"
    "\n"
    "    // Persistent list container — only its children are cleared /\n"
    "    // re-created in `renderList()`. The container itself is not replaced.\n"
    "    contentEl.createDiv({ cls: 'researchvault-sidebar-list' });\n"
    "\n"
    "    this.renderList();\n"
    "  }\n"
    "\n"
    "  /**\n"
    "   * Re-create only the paper list section. Safe to call on every state\n"
    "   * change; the header (with the focused search input) is left untouched\n"
    "   * so the user keeps typing without re-clicking the field.\n"
    "   */\n"
    "  private renderList(): void {\n"
    "    const listEl =\n"
    "      this.contentEl.querySelector<HTMLElement>('.researchvault-sidebar-list');\n"
    "    if (!listEl) {\n"
    "      // View not yet opened (or full render was bypassed). Fall back to a\n"
    "      // full render so the header + list container get mounted.\n"
    "      this.render();\n"
    "      return;\n"
    "    }\n"
    "    listEl.replaceChildren();\n"
    "\n"
    "    const active = this.rv.projectManager.getActiveProject();\n"
    "    if (!active) {\n"
    "      listEl.createEl('p', {\n"
    "        text: 'No active project. Use the \"switch active project\" command to pick one.',\n"
    "        cls: 'researchvault-sidebar-empty',\n"
    "      });\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    const papers = this.rv.paperService.getInProject(active.id);\n"
    "    if (papers.length === 0) {\n"
    "      listEl.createEl('p', {\n"
    "        text: 'No papers in this project yet. Use \"add paper\" to import one.',\n"
    "        cls: 'researchvault-sidebar-empty',\n"
    "      });\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // When the user has typed a query, the indexer gives us a fuzzy-matched\n"
    "    // subset across the whole vault. We still constrain by active project\n"
    "    // membership at render time so the user never sees a paper from a\n"
    "    // different project mixed in.\n"
    "    const trimmed = this.currentQuery.trim();\n"
    "    if (trimmed) {\n"
    "      const hits = this.rv.vaultIndexer.searchPapers(trimmed);\n"
    "      const activePapers = new Set(papers.map((p) => p.id));\n"
    "      const scoped = hits.filter((p) => activePapers.has(p.id));\n"
    "      if (scoped.length === 0) {\n"
    "        listEl.createEl('p', {\n"
    "          text: `No papers match \"${trimmed}\" in this project.`,\n"
    "          cls: 'researchvault-sidebar-empty',\n"
    "        });\n"
    "        return;\n"
    "      }\n"
    "      this.renderGroup(listEl, 'results', scoped);\n"
    "      return;\n"
    "    }\n"
    "\n"
    "    // Derived \"Needs action\" group. Computed every render (cheap; it's just\n"
    "    // a filter + sort over the in-memory list). Empty -> nothing rendered.\n"
    "    const needsAction = computeNeedsAction(papers);\n"
    "    if (needsAction.length > 0) {\n"
    "      this.renderGroup(listEl, 'needs-action', needsAction);\n"
    "    }\n"
    "\n"
    "    const groups = groupByStatus(papers);\n"
    "    for (const status of STATUS_ORDER) {\n"
    "      const rows = groups.get(status);\n"
    "      if (!rows || rows.length === 0) continue;\n"
    "      this.renderGroup(listEl, status, rows);\n"
    "    }\n"
    "  }\n"
)
assert src.count(old_body_start) == 1, f"render body not found uniquely ({src.count(old_body_start)})"
src = src.replace(old_body_start, new_body_start, 1)

ROOT.write_text(src)
print("OK sidebar refactor")
