import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

// Copy the pdfjs-dist worker file to the output directory so it can be loaded at runtime.
import fs from 'node:fs';
import path from 'node:path';

const workerSrc = path.resolve(process.cwd(), 'node_modules/pdfjs-dist/build/pdf.worker.min.mjs');
const workerDest = path.resolve(process.cwd(), 'pdf.worker.min.mjs');

if (prod) {
	await context.rebuild();
	fs.copyFileSync(workerSrc, workerDest);
	process.exit(0);
} else {
	await context.watch();
	// Watch the worker file and copy on change.
	let lastCopy = 0;
	setInterval(() => {
		try {
			const stat = fs.statSync(workerSrc);
			if (stat.mtimeMs > lastCopy) {
				fs.copyFileSync(workerSrc, workerDest);
				lastCopy = Date.now();
			}
		} catch { /* ignore */ }
	}, 2000);
}
