// src/types/notes.ts

export interface LiteratureNote {
  paperId: string;
  paperCitekey: string;
  
  // Structured sections (each can be a heading in the note)
  summary?: string;
  keyPoints: string[];
  methodology?: string;
  results?: string;
  critique?: string;
  relevance?: string;              // To my research
  questions: string[];
  connections: string[];             // Links to other notes/papers
  
  // Generated by AI or manual
  atomicNotes: AtomicNote[];
}

export interface AtomicNote {
  id: string;
  content: string;
  sourcePaperId: string;
  sourceQuoteId?: string;
  tags: string[];
  createdAt: number;
}

export interface ConceptNote {
  id: string;
  name: string;
  description: string;
  definition?: string;
  
  // Aggregated from papers
  claims: ConceptClaim[];
  relatedConcepts: string[];       // Links to other concepts
  papers: string[];                // Papers discussing this concept
  
  // Graph position (optional)
  position?: { x: number; y: number };
}

export interface ConceptClaim {
  paperId: string;
  claimId: string;
  stance: 'supports' | 'contradicts' | 'neutral';
  evidence: string;
}